finalportfolio/urls.py
from django.urls import path
from . import views
app_name='finalportfolio'
urlpatterns = [
    path ('',views.index,name='index'),
    path ('work/',views.work,name='work'),
      path ('projects/',views.projects,name='projects'),
]

polls/urls.py
from django.urls import path
from . import views
app_name='polls'
urlpatterns = [
    path ('',views.index,name='index'),
    
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('project/', views.project1, name='project'),
    path('work/', views.work1, name='work'),
    path('<int:id>/blog/', views.blog, name='blog'),



]

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
# from polls.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('polls',hello),
    path("",include('finalportfolio.urls')),
    path("portfolio/",include('polls.urls'))
]

finalportfolio/models.py
import datetime
from time import timezone

from django.db import models

class Projects(models.Model):
	start = models.DateField('start date')
	end = models.DateField('end date')
	name = models.CharField(max_length=200)
	skills = models.CharField(max_length=200)
	description = models.CharField(max_length=2000)
	ongoing = models.BooleanField(default=True)
	image = models.ImageField(upload_to="static/finalportfolio/images",default="image.jpeg")

polls/models.py
import datetime
from time import timezone

from django.db import models
from enum import Enum

class work(models.Model):
    start = models.DateField('start date')
    end = models.DateField('end date')
    place = models.CharField(max_length=200)
    position = models.CharField(max_length=200)
    description = models.TextField(max_length=2000)
    def __str__(self):
        return self.position + " " +self.place




class project(models.Model):
    start = models.DateField('start date')
    end = models.DateField('end date')
    name = models.CharField(max_length=200)
    skills = models.CharField(max_length=200)
    description = models.CharField(max_length=2000)
    photo = models.CharField(max_length= 2000)

    def __str__(self):
        return self.skills + " " + self.name
class Level(models.TextChoices):   # A subclass of Enum
    l1 = "level 1"
    l2 = 'level 2'
    l3 = 'level 3'
    l4 = 'level 4'
    l5 = 'level 5'
    l6 = 'intermediate'

class Type(models.TextChoices):   # A subclass of Enum
    lang='Language'
    web='Web/ Framework / App'
    har='Hard Skills'


class skills(models.Model):
    # types = ('learning','basic','intermediate','advanced','expert')
    level = models.IntegerField(default=0)
    description = models.CharField(max_length=2000)
    type = models.CharField(
        max_length=40,
        choices=Type.choices , # Cho# ices is a list of Tuple
        default=Type.lang
    )
    def __str__(self):
        return  self.description + self.type

finalportfolio/views.py
from django.shortcuts import render
from .models import Projects

def index(request):
    return render(request, 'finalportfolio/index.html', {}) 

def work(request):
    return render(request, 'finalportfolio/work.html', {}) 

def projects(request):
    work1 = Projects.objects.order_by('-start')
    return render(request, 'finalportfolio/projects.html', {'projects':work1})

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
# Create your views here.
from django.http import HttpResponse, Http404 ,HttpResponseRedirect
from .models import work,project, skills
from django.template import loader
from django.template.defaulttags import register

@register.filter
def get_range(value):
    return range(int(value))
@register.filter

def get_rangeq(value):
    return range(5-int(value))
# Create your tests here.
@register.filter
def split(value):
    return value.split('\n')
# Create your tests here.
def index(request):
    work1 = skills.objects.order_by('-level')
    return render(request, 'polls/index.html', {'skills':work1})
def project1(request):
    return render(request, 'polls/about.html', {})
def blog(request,id):
    work1 = project.object.get(pk=id)
    return render(request, 'polls/blog.html', {'project':work1})
def work1(request):
    work1 = work.objects.order_by('-end')
    return render(request, 'polls/collection.html', {'works':work1})
def services(request):
    return render(request, 'polls/services.html', {})
def single(request):
    return render(request, 'polls/single.html', {})
def contact(request):
    return render(request, 'polls/contact.html', {})


def detail(request, question_id):
    return render(request, 'polls/detail.html', {})


def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

finalportfolio/templates/finalportfolio/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Muhammad Moied</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
   {% load static %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <style type="text/css">
  	html *
{
   font-family: Courier New !important;
   font-size: 18px
}
img.icon{
border-radius: 20px;
max-width: 40px
}
  </style>
</head>
<body style="background-color:#222831;"> 
	 <div class="container text-center" style="margin-top: 2%;background-color: #393e46;border-radius: 20px">
	<nav class="navbar navbar-expand-md navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href="{% url 'finalportfolio:index' %}" style="xfont-size: 30px">Muhammad Moied</a>

  <!-- Toggler/collapsibe Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar" name="menu">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
      <a class="nav-link" style="color:#00dfeb"href="{% url 'finalportfolio:work' %}">Work Experience</a>
    </li>
    <li class="nav-item">
      <a class="nav-link"style="color: #00dfeb" href="{% url 'finalportfolio:projects' %}">Projects</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " style="color: #00dfeb" href="{% static 'polls/Muhammad Moied.pdf' %}" target="_blank">Open CV</a>
    </li>
    </ul>
  </div> 
</nav>
</div>
 <!--  <h1 class="text-center" style="color: #eeeeee;font-size: 40px";>Muhammad Moied</h1>
   <div class="container text-center" style="margin-top: 2%;background-color: #393e46;border-radius: 20px">
  <ul class="nav justify-content-center">
    <li class="nav-item">
      <a class="nav-link disabled" style="color: #eeeeee" href="#">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" style="color:#00adb5"href="{% url 'finalportfolio:work' %}">Work Experience</a>
    </li>
    <li class="nav-item">
      <a class="nav-link"style="color: #00adb5" href="#">Projects</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " style="color: #00adb5" href="{% static 'polls/Muhammad Moied.pdf' %}" target="_blank">Open CV</a>
    </li>
  </ul>
</div> -->
  <div class="container text-left mw-75" style="margin-top: 2%;background-color: #393e46;border-radius: 20px;color: white;padding: 20px">
   <div class="row">
    <div class="col-sm-9" style="padding-bottom: 15px">
    	<h1 class="signature h2" style=" color: #eeeeee">About Me</h1>
An ambitious software engineer with 3 years of experience in object-oriented and functional programming, database
management and app development.<br> I am a final year BSc-Computer Science(Hons) student in
Heriot Watt University, Dubai. <br>Seeking an opportunity that allows me to utilize my problem-solving, analytical
skills and my programming knowledge.
	<h3 class="signature h3" style="color: #eeeeee">Connect</h3>
	
	<a href="https://github.com/moied12" target="_blank">
		<img src=" {% static 'finalportfolio/images/github.ico'  %}"   class="icon" alt="Muhammad Moied" >
	</a>
	<a href="https://ae.linkedin.com/in/muhammad-moied-poonawala?trk=public_profile_browsemap_profile-result-card_result-card_full-click" target="_blank">
		<img src=" {% static 'finalportfolio/images/linkedin.ico'  %}" class="icon"  alt="Muhammad Moied" >
	</a>
	<a href="https://www.instagram.com/moieds/?hl=en" target="_blank">
		<img src=" {% static 'finalportfolio/images/instagram.ico'  %}"  class="icon" alt="Muhammad Moied" >
	</a>
	<a href="https://www.facebook.com/moied.sattar.3" target="_blank">
		<img src=" {% static 'finalportfolio/images/facebook.ico'  %}"  class="icon" alt="Muhammad Moied" >
	</a>
	<a href="https://twitter.com/MoiedSattar?s=08" target="_blank">
<img src=" {% static 'finalportfolio/images/twitter.ico'  %}" class="icon"  alt="Muhammad Moied" >
	</a>


    </div>
    <div class="col-sm-3" >
    	<img src=" {% static 'finalportfolio/images/author-2.jpg'  %}"  class="mx-auto d-block img-fluid" alt="Muhammad Moied" style="max-width: 70%;border-radius: 10%;">
    </div>
  </div>
</div>


  <div class="container text-left mw-75" style="margin-top: 2%;background-color: #393e46;border-radius: 20px;color: white;padding: 20px">
  	    	<h1 class="signature h2" style=" color: #eeeeee">Education</h1>
   <div class="row">
    <div class="col-sm-9">
    	<p>
		<p style="color: #00dfeb;">BSc Hons - Computer Science</p>
		Heriot Watt University, Dubai
		<br>3rd year completed with Cumulative GPA 4.0</p>
    </div>
    <div class="col-sm-3" >
    	<span style="color:#00dfeb;">(2018-2021)</span>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-9">
    		<p>
    	<p style="color: #00dfeb;">A levels</p>
		The Westminster School, Dubai
		<br>Mathematics-A Computer Science-A Physics-B </p>
    		</p>
    </div>
    <div class="col-sm-3" >
    	<span style="color:#00dfeb;">(2018-2021)</span>
    </div>
  </div>
</div>


  <div class="container text-left mw-75" style="margin-top: 2%;background-color: #393e46;border-radius: 20px;color: white;padding: 20px">
		<div class="row mb-5" style="margin-bottom: 0px">
		  <div class="col-md">
			 <h3 class="signature h4" style="color: #eeeeee">Certification</h3>
			  <p style="color:white "><span style="color:#00dfeb ">Flutter:</span> <br>The Complete 2020 Flutter Development Bootcamp with Dart </p>
			  <p style="color:white "><span style="color:#00dfeb ">Python:</span>  <br>Machine Learning, Data Science and Deep Learning with Python  </p>

		  </div>
			<div class="col-md">
				<h3 class="signature h4" style="color: white">Awards</h3>
				<p style="color:white "><span style="color:#00dfeb ">Deputy Principal’s Award</span> (Academic Excellence), <br>Heriot Watt University</p>
				<p style="color:white "><span style="color:#00dfeb ">Best Sixth Former of the Year,</span> <br>The Westminster School, Dubai</p>
		  </div>
			<div class="col-md">
				<h3 class="signature h4" style="color: white">Additional Information</h3>
				<p style="color:white "> <span style="color:#00dfeb ">Proficient in English & Urdu.</span></p>
				<p style="color:white "> <span style="color:#00dfeb ">Interests: -</span> <br>squash, <br>table tennis,<br>billiards, <br>hockey</p>
		  </div>
		</div>
</div>
</body>
</html>

finalportfolio/templates/finalportfolio/projects.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Muhammad Moied</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
   {% load static %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <style type="text/css">
  	html *
{
   font-family: Courier New !important;
   font-size: 18px
}
img.icon{
border-radius: 20px;
max-width: 40px
}
  </style>
</head>
<body style="background-color:#222831;"> 
	 <div class="container text-center" style="margin-top: 2%;background-color: #393e46;border-radius: 20px">
	<nav class="navbar navbar-expand-md navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href="{% url 'finalportfolio:index' %}" style="font-size: 30px">Muhammad Moied</a>

  <!-- Toggler/collapsibe Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar" name="menu">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
      <a class="nav-link" style="color:#00dfeb"href="{% url 'finalportfolio:work' %}">Work Experience</a>
    </li>
    <li class="nav-item">
      <a class="nav-link"style="color: #00dfeb" href="#">Projects</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " style="color: #00dfeb" href="{% static 'polls/Muhammad Moied.pdf' %}" target="_blank">Open CV</a>
    </li>
    </ul>
  </div> 
</nav>
</div>
   {% if projects %}
   {% for project in projects %}
        <div class="container text-left mw-75" style="margin-top: 2%;background-color: #393e46;border-radius: 20px;color: white;padding: 20px">
   <div class="row">
    <div class="col-sm-9" style="padding-bottom: 15px">
    	<h1 class="signature h1" style=" color: #eeeeee">{{ project.name }}</h1>
        <h4 class="signature h4"style="color:#00dfeb;"> ({{ project.skills }})</h4>
        {{ project.description}}
    </div>
    <div class="col-sm-3" >
        <span style="color:#00dfeb;font-size: 16px ">({{ project.start }}-{{ project.end }})</span>
<img src=" {% static ' project.image.url | safe '  %}"   class="icon" alt="Muhammad Moied" >


    </div>
  </div>
</div>
     {% endfor %}
       {% else %}
       No Projects
     {% endif %}


</body>
</html>

finalportfolio/templates/finalportfolio/work.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Muhammad Moied</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
   {% load static %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <style type="text/css">
  	html *
{
   font-family: Courier New !important;
   font-size: 18px
}
img.icon{
border-radius: 20px;
max-width: 40px
}
  </style>
</head>
<body style="background-color:#222831;"> 
   <div class="container text-center" style="margin-top: 2%;background-color: #393e46;border-radius: 20px">
  <nav class="navbar navbar-expand-md navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href="{% url 'finalportfolio:index' %}" style="font-size: 30px">Muhammad Moied</a>

  <!-- Toggler/collapsibe Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar" name="menu">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
      <a class="nav-link" style="color:#00dfeb"href="{% url 'finalportfolio:work' %}">Work Experience</a>
    </li>
    <li class="nav-item">
      <a class="nav-link"style="color: #00dfeb" href="{% url 'finalportfolio:projects' %}">Projects</a>
    </li>
    <li class="nav-item">
      <a class="nav-link " style="color: #00dfeb" href="{% static 'polls/Muhammad Moied.pdf' %}" target="_blank">Open CV</a>
    </li>
    </ul>
  </div> 
</nav>
</div>
  <div class="container text-left mw-75" style="margin-top: 2%;background-color: #393e46;border-radius: 20px;color: white;padding: 20px">
  	    	<h1 class="signature h2" style=" color: white ;">Grandeur Luxury</h1>
   <div class="row">
    <div class="col-sm-8">
    	<p>
		<p style="color: #00dfeb;font-size: 20px">Flutter Developer</p>
    <ul>
      <li>Worked on a limousine service app bundle using Flutter, Dart and Typescript</li>
       <li>Consisted of Customer, Driver and Admin android, ios and web app</li>
        <li>Added functionality to customer and driver app UI kit</li>
         <li>Worked with google cloud functions and Firebase for responsiveness</li>
          <li>Used google maps API for added functionality</li>
            </ul>
            Links To App
            <br>
            <a class="nav-link"style="color: #00dfeb" href="https://play.google.com/store/apps/details?id=com.grandeur.taxiDriver" target="_blank">Android Driver App</a>
            <a class="nav-link"style="color: #00dfeb" href="https://play.google.com/store/apps/details?id=com.grandeur.taxiCustomer" target="_blank">Android Customer App</a>
              <a class="nav-link"style="color: #00dfeb" target="_blank"href="https://apps.apple.com/ae/app/grandeur-limousine/id1522503218">iOS Customer App</a>
          </p>
    </div>
    <div class="col-sm-4" >
    	<span style="color:#00dfeb;">June. 1, 2020 - July. 31, 2020</span>
    </div>
  </div>
</div>
  <div class="container text-left mw-75" style="margin-top: 2%;background-color: #393e46;border-radius: 20px;color: white;padding: 20px">
          <h1 class="signature h2" style=" color: white ;">Al Moiz Textiles</h1>
   <div class="row">
    <div class="col-sm-8">
      <p>
    <p style="color: #00dfeb;font-size: 20px">Django Web Developer</p>
    <ul>
      <li>Account and Financial Analysis System</li>
       <li>Designed database and UI</li>
        <li>Data population from older CSV files to database</li>
         <li>Developed Django web app to compute data</li>
            </ul>
          </p>
    </div>
    <div class="col-sm-4" >
      <span style="color:#00dfeb;">Jan. 1, 2019 - June 30, 2019</span>
    </div>
  </div>
</div>
</body>
</html>

polls/templates/polls/about.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Muhammad Moied</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Herr+Von+Muellerhoff" rel="stylesheet">

 	    {% load static %}
    <link rel="stylesheet" href=" {% static 'polls/css/open-iconic-bootstrap.min.css' %} ">
    <link rel="stylesheet" href="{% static 'polls/css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'polls/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'polls/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'polls/css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'polls/css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'polls/css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'polls/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'polls/css/jquery.timepicker.css' %}">


    <link rel="stylesheet" href="{% static 'polls/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'polls/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'polls/css/style.css' %}">
  </head>
  <body>

	<div id="colorlib-page">
		<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
			<aside id="colorlib-aside" role="complementary" class="js-fullheight text-center" style="background-color: black;		">
			<h1 id="colorlib-logo"><a href="{% url 'polls:index' %}"><span class="img" style="background-image: url(../../static/polls/images/author-2.jpg);"></span><div style="color: #fc0fc0">Muhammad Moied</div></a></h1>
			<nav id="colorlib-main-menu" role="navigation">
				<ul >
					<li ><a href="{% url 'polls:index' %}" style="color: #fc0fc0">Home</a></li>
					<li ><a href="{% url 'polls:work' %}" style="color: #fc0fc0">Work History</a></li>
					<li><a href="{% url 'polls:project' %}" style="color: #fc0fc0;text-decoration: underline; ">Projects</a></li>
					<li><a href="{% static 'polls/Muhammad Moied.pdf' %}" target="_blank"style="color: #fc0fc0" >Open CV</a></li>
					<li><a href="#bottom" style="color: #fc0fc0">Contact</a></li>
				</ul>
			</nav>
		</aside>
		<div id="colorlib-main"  style="background-color:#A2A4AA ">
			<section class="ftco-section ftco-bread" >
				<div class="container" >
					<div class="row no-gutters slider-text justify-content-center align-items-center">
	          <div class="col-md-8 ftco-animate">
	            <p class="breadcrumbs"><span class="mr-2"><a href={% url 'polls:index' %}>Home</a></span> <span>Projects</span></p>
				  <h1 class="bread" style="color:#A2A4AA;">My Projects</h1>
				  {% if works %}
				  <ul>
					  {% for work in works%}
					  <li> {{ work.place }}</li>
					  <li>{{ work.position }}</li>
					  <li>{{ work.description }}</li>
					  {% endfor %}
				  </ul>
					{% else %}
						<p>No polls are available.</p>
					{% endif %}
	          </div>
	        </div>
				</div>
			</section>
	     <footer class="ftco-footer ftco-bg-dark ftco-section" id="bottom" style="background-color:#A2A4AA;">
	      <div class="container px-md-5">
	        <div class="row mb-5" >
	          <div class="col-md">
	             <div class="ftco-footer-widget mb-4">
	              <h2 class="ftco-heading-2">On Going Projects</h2>
	              <ul class="list-unstyled categories">
	              	<li><a href="#">November 2018 <span>(105)</span></a></li>
	              </ul>
	            </div>
	          </div>
	          <div class="col-md">
	            <div class="ftco-footer-widget mb-4">
	            	<h2 class="ftco-heading-2">Have a Question?</h2>
	            	<div class="block-23 mb-3">
		              <ul>
					<li><a href="#"><span class="icon icon-phone"></span><span class="text">+971 52 705 9570</span></a></li>
		                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">moied90@hotmail.com</span></a></li>
		              </ul>
		            </div>
	            </div>
	          </div>
	        </div>
	        <div class="row">
	          <div class="col-md-12">
    </div>
	        </div>
	      </div>
	    </footer>

		</div>
	</div>

  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>
 <script src="{% static 'polls/js/jquery.min.js' %}"></script>
  <script src="{% static 'polls/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'polls/js/popper.min.js' %}"></script>
  <script src="{% static 'polls/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'polls/js/jquery.easing.1.3.j' %}s"></script>
  <script src="{% static 'polls/js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'polls/js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'polls/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'polls/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'polls/js/aos.js' %}"></script>
  <script src="{% static 'polls/js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'polls/js/bootstrap-datepicker.js' %}"></script>
  <script src="{% static 'polls/js/jquery.timepicker.min.js' %}"></script>
  <script src="{% static 'polls/js/scrollax.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'polls/js/google-map.js' %}"></script>
  <script src="{% static 'polls/js/main.js' %}"></script>
    
  </body>
</html>